name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide the following information to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen.
      placeholder: I would like the formatter to...
    validations:
      required: true

  - type: textarea
    id: user-value
    attributes:
      label: User Value
      description: Why would this feature be useful? What problem does it solve?
      placeholder: This would help users by...
    validations:
      required: true

  - type: textarea
    id: current-alternative
    attributes:
      label: Current Workaround
      description: How are you currently handling this use case, if at all?
      placeholder: Currently I have to manually...

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas about how this could be implemented, share them here
      placeholder: This could be implemented by adding...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work
      render: gdscript
      placeholder: |
        # Example of how the feature would work
        # Input:
        func example():
            pass

        # Output after feature:
        func example():
            pass

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here